# -*- coding: utf-8 -*-
"""
Created on Mon Feb 06 12:26:58 2017

@author: Gebruiker
"""
from __future__ import division
"""
Programming Preparation
"""

import numpy as np
import pandas as pd
import datetime as dt
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
"""
Data Structure
"""
def _parse_date(date_str, format_str):
    time_dt = dt.datetime.strptime(date_str, format_str)
    return [time_dt.year, time_dt.month, time_dt.day, time_dt.weekday, time_dt.time()]

Universal = pd.read_csv('D:\School\School\Master\Jaar_1\Machine Learning in Practice\Competition\Data\Merge\Universal\Universal_with_labels.csv', index_col = 0, dtype={'gender': object, 'group': str, 'phone_brand': str, 'device_model': str})
Gerdriaan = pd.read_csv('D:\School\School\Master\Jaar_1\Machine Learning in Practice\Competition\Data\Noise Eliminated Universal Files\events_combined.csv', index_col = 0, dtype={'gender': object, 'group': str, 'phone_brand': str, 'device_model': str})
gender = pd.read_csv('D:/School/School/Master/Jaar 1/Machine Learning in Practice/Competition/Data/Mobile Data/gender_age_train.csv')
Universal.age.describe()

A = Universal
B = Gerdriaan

A.head(100)
B.head(100)

B.columns

sns.distplot(Universal.age.dropna(), color='#63EA55')
width = 1
axes = plt.gca()
axes.set_ylim([0.00,0.10])
axes.set_xlim([15,90])
plt.xlabel('Age')
sns.despine()
plt.show

Universal.drop('gender', inplace=True, axis=1)
Universal.drop('group', inplace=True, axis=1)
Universal.drop('age', inplace=True, axis=1)

Device_properties = Universal
Device_properties.to_csv('Device_properties.csv')

brand_model = pd.read_csv('D:/School/School/Master/Jaar 1/Machine Learning in Practice/Competition/Data/Mobile Data/phone_brand_device_model.csv')

brand_model.replace('三星', 'SAMSUNG', inplace=True)
brand_model.replace('华为', 'HUAWEI', inplace=True)
brand_model.replace('小米', 'XIAOMI', inplace=True)
brand_model.replace('vivo', 'VIVO', inplace=True)
brand_model.replace('魅族', 'MEIZU', inplace=True)
brand_model.replace('酷派', 'NOKIA', inplace=True)
brand_model.replace('天语', 'SAMSUNG-JITTERBUG', inplace=True)
brand_model.replace('金立', 'GIONEE', inplace=True)
brand_model.replace('联想', 'LENOVO', inplace=True)
brand_model.replace('海信', 'HISENSE', inplace=True)
brand_model.replace('索尼', 'SONY', inplace=True)
brand_model.replace('酷比', 'SAMSUNG-GALAXY', inplace=True)
brand_model.replace('中兴', 'LG', inplace=True)
brand_model.replace('康佳', 'ZTE', inplace=True)
brand_model.replace('旗舰版', 'Ultimate', inplace=True)
brand_model.replace('奇酷', 'QI-Cool', inplace=True)
brand_model.replace('欧博信', 'OPPSON', inplace=True)
brand_model.replace('欧比', 'LG', inplace=True)
brand_model.replace('爱派尔', 'CHINESE', inplace=True)
brand_model.replace('努比亚', 'SONY-EXPERIA', inplace=True)
brand_model.replace('优米', 'XIAOMI', inplace=True)
brand_model.replace('朵唯', 'SAMSUNG-GALAXY', inplace=True)
brand_model.replace('黑米', 'GEOTEL', inplace=True)
brand_model.replace('努比亚', 'ZTE-NUBIA', inplace=True)
brand_model.replace('锤子', 'SMARTISAN', inplace=True)
brand_model.replace('朵唯', 'HYUNDAI', inplace=True)
brand_model.replace('酷比魔方', 'CUBE-TALK', inplace=True)
brand_model.replace('E人E本', 'PANASONIC', inplace=True)
brand_model.replace('E派', 'TELSTRA', inplace=True)
brand_model.replace('一加', 'NOKIA', inplace=True)
brand_model.replace('世纪天元', 'Century-Tianyuan', inplace=True)
brand_model.replace('中国移动', 'ZONG', inplace=True)
brand_model.replace('世纪星', 'INTEX-AQUA', inplace=True)
brand_model.replace('乐视', 'LE-PRO', inplace=True)  
brand_model.replace('乡米', 'XMKJ', inplace=True)  
brand_model.replace('亚马逊', 'AMAZON-FIRE PHONE', inplace=True)  
brand_model.replace('亿通', 'CHINESE', inplace=True) 
brand_model.replace('优语', 'KDOOR', inplace=True) 
brand_model.replace('优购', 'CHINESE', inplace=True) 
brand_model.replace('先锋', 'PIONEER', inplace=True) 
brand_model.replace('凯利通', 'PANASONIC', inplace=True) 
brand_model.replace('华硕', 'ASUS', inplace=True) 
brand_model.replace('原点', 'ORIGINAL', inplace=True) 
brand_model.replace('台电', 'TECLAST', inplace=True) 
brand_model.replace('唯米', 'HUAWEI', inplace=True) 
brand_model.replace('基伍', 'BAIMI', inplace=True) 
brand_model.replace('夏新', 'AMOI', inplace=True) 
brand_model.replace('大Q', 'CHINESE', inplace=True)
brand_model.replace('大可乐', 'DAKELE', inplace=True)
brand_model.replace('大显', 'HUAWEI-HONOR', inplace=True)
brand_model.replace('天宏时代', 'TIANHONG-TIMES', inplace=True)
brand_model.replace('奥克斯', 'AUX', inplace=True)
brand_model.replace('宏碁', 'ACER', inplace=True)
brand_model.replace('宏碁', 'BASICOM', inplace=True)
brand_model.replace('富可视', 'VOXTEL', inplace=True)
brand_model.replace('小杨树', 'SHENZHEN-XIAOYANGSHU-COMMUNICATION', inplace=True)
brand_model.replace('尼比鲁', 'NIBURU', inplace=True)
brand_model.replace('帷幄', 'LAVA-IRIS', inplace=True)
brand_model.replace('广信', 'ADVAN-BARCA-5', inplace=True)
brand_model.replace('德卡诺', 'LANDVO', inplace=True)
brand_model.replace('德赛', 'DESAY', inplace=True)
brand_model.replace('恒宇丰', 'KOU-FENG-HYF', inplace=True)
brand_model.replace('惠普', 'HP', inplace=True)
brand_model.replace('戴尔', 'DELL', inplace=True)
brand_model.replace('摩托罗拉', 'LENOVO', inplace=True)
brand_model.replace('斐讯', 'PHICOMM', inplace=True)
brand_model.replace('昂达', 'ONDA', inplace=True)
brand_model.replace('易派', 'SONY-XPERIA', inplace=True)
brand_model.replace('普耐尔', 'PLOYER', inplace=True)
brand_model.replace('智镁', 'ROLAND', inplace=True)
brand_model.replace('智镁', 'VIVO', inplace=True)
brand_model.replace('极米', 'i-STATION', inplace=True)
brand_model.replace('果米', 'SAMSUNG-GALAXY', inplace=True)
brand_model.replace('梦米', 'HUAWEI-ASCEND', inplace=True)
brand_model.replace('欧乐迪', 'i-MOBILE', inplace=True)
brand_model.replace('欧乐酷', 'CBSKY-UWATCH', inplace=True)
brand_model.replace('欧奇', 'OU QI', inplace=True)
brand_model.replace('沃普丰', 'SAMSUNG-GALAXY', inplace=True)
brand_model.replace('波导', 'HCR', inplace=True)
brand_model.replace('海尔', 'HAIER', inplace=True)
brand_model.replace('瑞米', 'VIVO', inplace=True)
brand_model.replace('瑞高', 'MUCH', inplace=True)
brand_model.replace('白米', 'HKS', inplace=True)
brand_model.replace('百加', 'X-BO', inplace=True)
brand_model.replace('百立丰', 'LI-FENG', inplace=True)
brand_model.replace('神舟', 'HASEE', inplace=True)
brand_model.replace('米奇', 'GAMMA', inplace=True)
brand_model.replace('米歌', 'SEAGULL', inplace=True)
brand_model.replace('糖葫芦', 'THL', inplace=True)
brand_model.replace('糯米', 'XIAOMI-REDMI', inplace=True)
brand_model.replace('纽曼', 'NEWMAN', inplace=True)
brand_model.replace('维图', 'ORCELL', inplace=True)
brand_model.replace('美图', 'MEITU', inplace=True)
brand_model.replace('聆韵', 'PATENT', inplace=True)
brand_model.replace('至尊宝', 'CHINA-QUADBAND-TV', inplace=True)
brand_model.replace('艾优尼', 'SAMSUNG', inplace=True)
brand_model.replace('蓝魔', 'RAMOS', inplace=True)
brand_model.replace('虾米', 'VIVO', inplace=True)
brand_model.replace('西米', 'XIMI-SIMI', inplace=True)
brand_model.replace('西门子', 'GIGASET-ME', inplace=True)
brand_model.replace('语信', 'SAMSUNG-GALAXY', inplace=True)
brand_model.replace('诺亚信', 'MAXIMUM', inplace=True)
brand_model.replace('诺基亚', 'OPPO', inplace=True)
brand_model.replace('谷歌', 'ASUS-GOOGLE', inplace=True)
brand_model.replace('贝尔丰', 'T-SERIES', inplace=True)
brand_model.replace('赛博宇华', 'SAIBOYUHUA', inplace=True)
brand_model.replace('邦华', 'OUKITEL', inplace=True)
brand_model.replace('酷珀', 'KOPO', inplace=True)
brand_model.replace('金星数码', 'VENUS-JXD', inplace=True)
brand_model.replace('长虹', 'GABA', inplace=True)
brand_model.replace('青橙', 'GREEN-ORANGE', inplace=True)
brand_model.replace('青葱', 'LAVA', inplace=True)
brand_model.replace('飞利浦', 'PHILIPS-XENIUM', inplace=True)
brand_model.replace('飞秒', 'PANASONIC', inplace=True)
brand_model.replace('首云', 'PEPSI', inplace=True)
brand_model.replace('鲜米', 'HI-TECH', inplace=True)

SAMSUNG = np.count_nonzero(brand_model.phone_brand == 'SAMSUNG')
HUAWEI = np.count_nonzero(brand_model.phone_brand == 'HUAWEI')
XIAMOI = np.count_nonzero(brand_model.phone_brand == 'XIAOMI')
VIVO = np.count_nonzero(brand_model.phone_brand == 'VIVO')
MEIZU = np.count_nonzero(brand_model.phone_brand == 'MEIZU')
NOKIA = np.count_nonzero(brand_model.phone_brand == 'NOKIA')
PEPSI = np.count_nonzero(brand_model.phone_brand == 'PEPSI')
PANASONIC = np.count_nonzero(brand_model.phone_brand == 'PANASONIC')
PHILIPSXENIUM = np.count_nonzero(brand_model.phone_brand == 'PHILIPS XENIUM')
LAVA = np.count_nonzero(brand_model.phone_brand == 'LAVA')
GREENORANGE = np.count_nonzero(brand_model.phone_brand == 'GREEN ORANGE')
GABA = np.count_nonzero(brand_model.phone_brand == 'GABA')
VENUS = np.count_nonzero(brand_model.phone_brand == 'VENUS JXD')
KOPO = np.count_nonzero(brand_model.phone_brand == 'KOPO')
OUKITEL = np.count_nonzero(brand_model.phone_brand == 'OUKITEL')
SAIBOYUHUA = np.count_nonzero(brand_model.phone_brand == 'SAIBOYUHUA')
TSERIES = np.count_nonzero(brand_model.phone_brand == 'T-SERIES')
ASUSGOOGLE = np.count_nonzero(brand_model.phone_brand == 'ASUS GOOGLE')
OPPO = np.count_nonzero(brand_model.phone_brand == 'OPPO')
MAXIMUM = np.count_nonzero(brand_model.phone_brand == 'MAXIMUM')
SAMSUNGGALAXY = np.count_nonzero(brand_model.phone_brand == 'SAMSUNG GALAXY')
GIGASET = np.count_nonzero(brand_model.phone_brand == 'GIGASET ME')
VIVO = np.count_nonzero(brand_model.phone_brand == 'XIMI SIMI')
RAMOS = np.count_nonzero(brand_model.phone_brand == 'RAMOS')
VIVO = np.count_nonzero(brand_model.phone_brand == 'VIVO')
CHINAQUADBANDTV = np.count_nonzero(brand_model.phone_brand == 'CHINA QUADBAND TV')
PATENT = np.count_nonzero(brand_model.phone_brand == 'PATENT')
MEITU = np.count_nonzero(brand_model.phone_brand == 'MEITU')
ORCELL = np.count_nonzero(brand_model.phone_brand == 'ORCELL')
NEWMAN = np.count_nonzero(brand_model.phone_brand == 'NEWMAN')
XIAOMIREDMI = np.count_nonzero(brand_model.phone_brand == 'XIAOMI REDMI')
THL = np.count_nonzero(brand_model.phone_brand == 'THL')
SEAGULL = np.count_nonzero(brand_model.phone_brand == 'SEAGULL')
GAMMA = np.count_nonzero(brand_model.phone_brand == 'GAMMA')
HASEE = np.count_nonzero(brand_model.phone_brand == 'HASEE')
LIFENG = np.count_nonzero(brand_model.phone_brand == 'LI FENG')
XBO = np.count_nonzero(brand_model.phone_brand == 'X-BO')
HKS = np.count_nonzero(brand_model.phone_brand == 'HKS')
MUCH = np.count_nonzero(brand_model.phone_brand == 'MUCH')
HAIER = np.count_nonzero(brand_model.phone_brand == 'HAIER')
HCR = np.count_nonzero(brand_model.phone_brand == 'HCR')
SAMSUNGGALAXY = np.count_nonzero(brand_model.phone_brand == 'SAMSUNG GALAXY')
OUQI = np.count_nonzero(brand_model.phone_brand == 'OU QI')
iMobile = np.count_nonzero(brand_model.phone_brand == 'i-Mobile')
HUAWEIASCEND = np.count_nonzero(brand_model.phone_brand == 'HUAWEI ASCEND')
iStation = np.count_nonzero(brand_model.phone_brand == 'i-Station')
ROLAND = np.count_nonzero(brand_model.phone_brand == 'ROLAND')
PLOYER = np.count_nonzero(brand_model.phone_brand == 'PLOYER')
SONYXPERIA= np.count_nonzero(brand_model.phone_brand == 'SONY XPERIA')
ONDA = np.count_nonzero(brand_model.phone_brand == 'ONDA')
PHICOMM= np.count_nonzero(brand_model.phone_brand == 'PHICOMM')
LENOVO = np.count_nonzero(brand_model.phone_brand == 'LENOVO')
DELL = np.count_nonzero(brand_model.phone_brand == 'DELL')
HP = np.count_nonzero(brand_model.phone_brand == 'HP')
KOUFENGHYF= np.count_nonzero(brand_model.phone_brand == 'KOU FENG HYF')
DESAY = np.count_nonzero(brand_model.phone_brand == 'DESAY')
LANDVO = np.count_nonzero(brand_model.phone_brand == 'LANDVO')
ADVANBARCA5 = np.count_nonzero(brand_model.phone_brand == 'ADVAN BARCA 5')
LAVAIRIS = np.count_nonzero(brand_model.phone_brand == 'LAVA IRIS')
NIBURU = np.count_nonzero(brand_model.phone_brand == 'NIBURU')
SHENZEN = np.count_nonzero(brand_model.phone_brand == 'SHENZHEN XIAOYANGSHU COMMUNICATION')
VOXTEL = np.count_nonzero(brand_model.phone_brand == 'VOXTEL')
BASICOM = np.count_nonzero(brand_model.phone_brand == 'BASICOM')
ACER = np.count_nonzero(brand_model.phone_brand == 'ACER')
AUX = np.count_nonzero(brand_model.phone_brand == 'AUX')
TIANHONG = np.count_nonzero(brand_model.phone_brand == 'TIANHONG TIMES')
HUAWEIHONOR = np.count_nonzero(brand_model.phone_brand == 'HUAWEI HONOR')
DAKELE = np.count_nonzero(brand_model.phone_brand == 'DAKELE')
CHINESE = np.count_nonzero(brand_model.phone_brand == 'CHINESE')
AMOI = np.count_nonzero(brand_model.phone_brand == 'AMOI')
BAIMI = np.count_nonzero(brand_model.phone_brand == 'BAIMI')
TECLAST = np.count_nonzero(brand_model.phone_brand == 'TECLAST')
ORIGINAL = np.count_nonzero(brand_model.phone_brand == 'ORIGINAL')
ASUS = np.count_nonzero(brand_model.phone_brand == 'ASUS')
KDOOR = np.count_nonzero(brand_model.phone_brand == 'KDOOR')
AMAZONFIREPHONE = np.count_nonzero(brand_model.phone_brand == 'AMAZON FIRE PHONE')
XMKJ = np.count_nonzero(brand_model.phone_brand == 'XMKJ')
LEPRO = np.count_nonzero(brand_model.phone_brand == 'LE PRO')
INTEXAQUA = np.count_nonzero(brand_model.phone_brand == 'INTEX AQUA')
ZONG = np.count_nonzero(brand_model.phone_brand == 'ZONG')
CenturyTianyuan =  np.count_nonzero(brand_model.phone_brand == 'Century Tianyuan')
NOKIA = np.count_nonzero(brand_model.phone_brand == 'NOKIA')
TELSTRA = np.count_nonzero(brand_model.phone_brand == 'TELSTRA')
CUBETALK = np.count_nonzero(brand_model.phone_brand == 'CUBE TALK')
HYUNDAI = np.count_nonzero(brand_model.phone_brand == 'HYUNDAI')
SMARTISAN = np.count_nonzero(brand_model.phone_brand == 'SMARTISAN')
ZTENUBIA = np.count_nonzero(brand_model.phone_brand == 'ZTE NUBIA')
GEOTEL = np.count_nonzero(brand_model.phone_brand == 'GEOTEL')
LG = np.count_nonzero(brand_model.phone_brand == 'LG')
OPPSON = np.count_nonzero(brand_model.phone_brand == 'OPPSON')
QICool = np.count_nonzero(brand_model.phone_brand == 'QI Cool')
Ultimate = np.count_nonzero(brand_model.phone_brand == 'Ultimate')
ZTE = np.count_nonzero(brand_model.phone_brand == 'ZTE')
GIONEE = np.count_nonzero(brand_model.phone_brand == 'GIONEE')
SAMSUNGJITTERBUG = np.count_nonzero(brand_model.phone_brand == 'SAMSUNG JITTERBUG')
QICool = np.count_nonzero(brand_model.phone_brand == 'QI Cool')







                

